language: node_js

sudo: false

node_js:
  - "0.12"

install:
  - npm install
  - npm install -g grunt-cli
before_script:
  - "npm update -g npm"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
